name: video-hosting
services:
  db:
    image: mysql:8.4.0
    container_name: video-db
    restart: unless-stopped
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PWD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PWD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - ./mysql-data:/var/lib/mysql
